version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: 
         command: python3 -m venv env && source ./env/bin/activate && pip install -r requirements.txt
         name: Build enviroment
      - run:
         command: pylint main.py
         name: Pylint
      - run:
          command: python3 test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
